apiVersion: v1
kind: Service
metadata:
  name: rpc-client-service
spec:
  selector:
    app: rpc-client
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: web
  - protocol: TCP
    port: 9494
    targetPort: 9494
    name: prometheus